"""
Posts review results back to a GitHub PR as a single summary comment.

Requires GITHUB_TOKEN with "Issues: Read and write" on the target repo —
PR comments use the issue-comments API endpoint under the hood, so that's
the permission GitHub checks, not "Pull requests".
"""

import os

import requests

from src.state import ReviewerOutput, TriageDecision

REPO_URL = "https://github.com/Ashkar-Noorul/pr-review-agents"


class GitHubWriterError(Exception):
    """Raised when posting a comment back to GitHub fails."""


def format_decision_as_markdown(
    decision: TriageDecision,
    security: ReviewerOutput = None,
    style: ReviewerOutput = None,
    logic: ReviewerOutput = None,
) -> str:
    lines = [
        "## 🤖 PR Review Agent — Automated Review",
        "",
        f"**Decision:** {decision.decision.upper()}",
        f"**Priority:** {decision.priority_score}/10",
        "",
        decision.summary,
    ]

    if decision.top_findings:
        lines += ["", "### Top findings"]
        for f in decision.top_findings:
            location = f" (`{f.file}:{f.line_hint}`)" if f.file and f.line_hint else ""
            lines.append(f"- **[{f.severity.upper()}]** `{f.category}`{location}: {f.message}")

    reviewer_sections = [("Security", security), ("Style", style), ("Logic", logic)]
    if any(output for _, output in reviewer_sections):
        lines += ["", "<details>", "<summary>Individual reviewer findings</summary>", ""]
        for name, output in reviewer_sections:
            if not output:
                continue
            lines.append(f"**{name}** — {output.summary}")
            for f in output.findings:
                lines.append(f"- [{f.severity}] `{f.category}`: {f.message}")
            lines.append("")
        lines.append("</details>")

    lines += [
        "",
        "---",
        f"*Generated by [pr-review-agents]({REPO_URL}) — a LangGraph multi-agent PR reviewer.*",
    ]
    return "\n".join(lines)


def post_pr_comment(owner: str, repo: str, pr_number: int, body: str) -> dict:
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise GitHubWriterError("GITHUB_TOKEN is not set in the environment.")

    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    response = requests.post(url, headers=headers, json={"body": body}, timeout=30)

    if response.status_code == 404:
        raise GitHubWriterError(f"PR not found: {owner}/{repo}#{pr_number}.")
    if response.status_code == 403:
        raise GitHubWriterError(
            "GitHub rejected the request (403) — your token likely needs "
            "'Issues: Read and write' permission on this repo."
        )
    if response.status_code == 401:
        raise GitHubWriterError("GitHub rejected the token — check GITHUB_TOKEN in .env.")
    response.raise_for_status()

    return response.json()
